<a href="https://colab.research.google.com/github/tomasrojas88/Data_Science_1/blob/main/Proyecto_Modulo2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importar librerías
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import warnings

In [ ]:
# Configuraciones opcionales para mejor visualización
sns.set_theme(style="whitegrid") # Establece un tema estético para los gráficos
plt.rcParams['figure.figsize'] = (12, 6) # Establece un tamaño de figura por defecto
warnings.filterwarnings('ignore') # Ignora advertencias (útil para presentaciones)

In [ ]:
import requests

url = "https://github.com/tomasrojas88/Data_Science_1/raw/refs/heads/main/Dataset%20Proyecto%20Coderhouse%20Satisfacci%C3%B3n%20Clientes%20en%20Aerolineas2.csv"

response = requests.get(url)  # Hace una solicitud GET para obtener el contenido del archivo
print(response.text[:300])  # Imprime los primeros 300 caracteres del archivo para ver cómo está delimitado
response = requests.get(url)  # Hace una solicitud GET para obtener el contenido del archivo
print(response.text[:300])  # Imprime los primeros 300 caracteres del archivo para ver cómo está delimitado

id_Encuesta;Identificación;Género;Tipo de Cliente;Edad;Tipo de Viaje;Clase;Distancia de Vuelo;Servicio de wifi a bordo;Hora de salida/llegada conveniente;Facilidad de reserva en línea;Ubicación de la puerta;Comida y bebida;Embarque en línea;Comodidad del asiento;Entretenimiento a bordo;Servicio a bo
id_Encuesta;Identificación;Género;Tipo de Cliente;Edad;Tipo de Viaje;Clase;Distancia de Vuelo;Servicio de wifi a bordo;Hora de salida/llegada conveniente;Facilidad de reserva en línea;Ubicación de la puerta;Comida y bebida;Embarque en línea;Comodidad del asiento;Entretenimiento a bordo;Servicio a bo

In [ ]:
df = pd.read_csv(url, sep=';', encoding='latin1') # lee el archivo,

df.head()# Muestra las primeras 5 filas

,id_Encuesta,Identificación,Género,Tipo de Cliente,Edad,Tipo de Viaje,Clase,Distancia de Vuelo,Servicio de wifi a bordo,Hora de salida/llegada conveniente,...,Entretenimiento a bordo,Servicio a bordo,Servicio de espacio para las piernas,Manejo de equipaje,Servicio de facturación,Servicio a bordo.1,Limpieza,Retraso en la salida en minutos,Retraso en la llegada en minutos,Satisfacción
0,0,19556,Femenino,Leal Cliente,52,Negocios Viaje,Eco,160,5,4,...,5,5,5,5,2,5,5,50,44.0,satisfecho/a
1,1,90035,Femenino,Leal Cliente,36,Negocios Viaje,Business,2863,1,1,...,4,4,4,4,3,4,5,0,0.0,satisfecho/a
2,2,12360,Masculino,Desleal Cliente,20,Negocios Viaje,Eco,192,2,0,...,2,4,1,3,2,2,2,0,0.0,neutral o insatisfecho/a
3,3,77959,Masculino,Leal Cliente,44,Negocios Viaje,Business,3377,0,0,...,1,1,1,1,3,1,4,0,6.0,satisfecho/a
4,4,36875,Femenino,Leal Cliente,49,Negocios Viaje,Eco,1182,2,3,...,2,2,2,2,4,2,4,0,20.0,satisfecho/a

In [ ]:
df.describe()  # Estadísticas básicas de columnas numéricas

,id_Encuesta,Identificación,Edad,Distancia de Vuelo,Servicio de wifi a bordo,Hora de salida/llegada conveniente,Facilidad de reserva en línea,Ubicación de la puerta,Comida y bebida,Embarque en línea,Comodidad del asiento,Entretenimiento a bordo,Servicio a bordo,Servicio de espacio para las piernas,Manejo de equipaje,Servicio de facturación,Servicio a bordo.1,Limpieza,Retraso en la salida en minutos,Retraso en la llegada en minutos
count,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.00000,25893.000000
mean,12987.500000,65005.657992,39.620958,1193.788459,2.724746,3.046812,2.756775,2.977094,3.215353,3.261665,3.449222,3.357753,3.385664,3.350169,3.633238,3.314175,3.649253,3.286226,14.30609,14.740857
std,7498.769632,37611.526647,15.135685,998.683999,1.335384,1.533371,1.412951,1.282133,1.331506,1.355536,1.320090,1.338299,1.282088,1.318862,1.176525,1.269332,1.180681,1.319330,37.42316,37.517539
min,0.000000,17.000000,7.000000,31.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.00000,0.000000
25%,6493.750000,32170.500000,27.000000,414.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,3.000000,3.000000,2.000000,0.00000,0.000000
50%,12987.500000,65319.500000,40.000000,849.000000,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,3.000000,4.000000,3.000000,0.00000,0.000000
75%,19481.250000,97584.250000,51.000000,1744.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,4.000000,5.000000,4.000000,5.000000,4.000000,12.00000,13.000000
max,25975.000000,129877.000000,85.000000,4983.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,1128.00000,1115.000000

In [ ]:
df.info()      # muestra tipos de datos y valores no nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25976 entries, 0 to 25975
Data columns (total 25 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   id_Encuesta                           25976 non-null  int64
 1   Identificación                        25976 non-null  int64
 2   Género                                25976 non-null  object
 3   Tipo de Cliente                       25976 non-null  object
 4   Edad                                  25976 non-null  int64
 5   Tipo de Viaje                         25976 non-null  object
 6   Clase                                 25976 non-null  object
 7   Distancia de Vuelo                    25976 non-null  int64
 8   Servicio de wifi a bordo              25976 non-null  int64
 9   Hora de salida/llegada conveniente    25976 non-null  int64
 10  Facilidad de reserva en línea         25976 non-null  int64
 11  Ubicación de la puerta                25976 non-null  int64
 12  Comida y bebida                       25976 non-null  int64
 13  Embarque en línea                     25976 non-null  int64
 14  Comodidad del asiento                 25976 non-null  int64
 15  Entretenimiento a bordo               25976 non-null  int64
 16  Servicio a bordo                      25976 non-null  int64
 17  Servicio de espacio para las piernas  25976 non-null  int64
 18  Manejo de equipaje                    25976 non-null  int64
 19  Servicio de facturación               25976 non-null  int64
 20  Servicio a bordo.1                    25976 non-null  int64
 21  Limpieza                              25976 non-null  int64
 22  Retraso en la salida en minutos       25976 non-null  int64
 23  Retraso en la llegada en minutos      25893 non-null  float64
 24  Satisfacción                          25976 non-null  object
dtypes: float64(1), int64(19), object(5)
memory usage: 5.0+ MB

In [ ]:
df.isnull().sum()  # Cuenta valores faltantes por columna

id_Encuesta                              0
Identificación                           0
Género                                   0
Tipo de Cliente                          0
Edad                                     0
Tipo de Viaje                            0
Clase                                    0
Distancia de Vuelo                       0
Servicio de wifi a bordo                 0
Hora de salida/llegada conveniente       0
Facilidad de reserva en línea            0
Ubicación de la puerta                   0
Comida y bebida                          0
Embarque en línea                        0
Comodidad del asiento                    0
Entretenimiento a bordo                  0
Servicio a bordo                         0
Servicio de espacio para las piernas     0
Manejo de equipaje                       0
Servicio de facturación                  0
Servicio a bordo.1                       0
Limpieza                                 0
Retraso en la salida en minutos          0
Retraso en la llegada en minutos        83
Satisfacción                             0
dtype: int64

In [ ]:
df["Retraso en la llegada en minutos"].fillna("No", inplace=True)##rellena los vacios con "No"

In [ ]:
df.isnull().sum()  # Cuenta valores faltantes por columna

id_Encuesta                             0
Identificación                          0
Género                                  0
Tipo de Cliente                         0
Edad                                    0
Tipo de Viaje                           0
Clase                                   0
Distancia de Vuelo                      0
Servicio de wifi a bordo                0
Hora de salida/llegada conveniente      0
Facilidad de reserva en línea           0
Ubicación de la puerta                  0
Comida y bebida                         0
Embarque en línea                       0
Comodidad del asiento                   0
Entretenimiento a bordo                 0
Servicio a bordo                        0
Servicio de espacio para las piernas    0
Manejo de equipaje                      0
Servicio de facturación                 0
Servicio a bordo.1                      0
Limpieza                                0
Retraso en la salida en minutos         0
Retraso en la llegada en minutos        0
Satisfacción                            0
dtype: int64

In [ ]:
df.info()      # muestra tipos de datos y valores no nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25976 entries, 0 to 25975
Data columns (total 25 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   id_Encuesta                           25976 non-null  int64
 1   Identificación                        25976 non-null  int64
 2   Género                                25976 non-null  object
 3   Tipo de Cliente                       25976 non-null  object
 4   Edad                                  25976 non-null  int64
 5   Tipo de Viaje                         25976 non-null  object
 6   Clase                                 25976 non-null  object
 7   Distancia de Vuelo                    25976 non-null  int64
 8   Servicio de wifi a bordo              25976 non-null  int64
 9   Hora de salida/llegada conveniente    25976 non-null  int64
 10  Facilidad de reserva en línea         25976 non-null  int64
 11  Ubicación de la puerta                25976 non-null  int64
 12  Comida y bebida                       25976 non-null  int64
 13  Embarque en línea                     25976 non-null  int64
 14  Comodidad del asiento                 25976 non-null  int64
 15  Entretenimiento a bordo               25976 non-null  int64
 16  Servicio a bordo                      25976 non-null  int64
 17  Servicio de espacio para las piernas  25976 non-null  int64
 18  Manejo de equipaje                    25976 non-null  int64
 19  Servicio de facturación               25976 non-null  int64
 20  Servicio a bordo.1                    25976 non-null  int64
 21  Limpieza                              25976 non-null  int64
 22  Retraso en la salida en minutos       25976 non-null  int64
 23  Retraso en la llegada en minutos      25976 non-null  object
 24  Satisfacción                          25976 non-null  object
dtypes: int64(19), object(6)
memory usage: 5.0+ MB

In [ ]:
df.info()      # muestra tipos de datos y valores no nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25976 entries, 0 to 25975
Data columns (total 25 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   id_Encuesta                           25976 non-null  int64
 1   Identificación                        25976 non-null  int64
 2   Género                                25976 non-null  object
 3   Tipo de Cliente                       25976 non-null  object
 4   Edad                                  25976 non-null  int64
 5   Tipo de Viaje                         25976 non-null  object
 6   Clase                                 25976 non-null  object
 7   Distancia de Vuelo                    25976 non-null  int64
 8   Servicio de wifi a bordo              25976 non-null  int64
 9   Hora de salida/llegada conveniente    25976 non-null  int64
 10  Facilidad de reserva en línea         25976 non-null  int64
 11  Ubicación de la puerta                25976 non-null  int64
 12  Comida y bebida                       25976 non-null  int64
 13  Embarque en línea                     25976 non-null  int64
 14  Comodidad del asiento                 25976 non-null  int64
 15  Entretenimiento a bordo               25976 non-null  int64
 16  Servicio a bordo                      25976 non-null  int64
 17  Servicio de espacio para las piernas  25976 non-null  int64
 18  Manejo de equipaje                    25976 non-null  int64
 19  Servicio de facturación               25976 non-null  int64
 20  Servicio a bordo.1                    25976 non-null  int64
 21  Limpieza                              25976 non-null  int64
 22  Retraso en la salida en minutos       25976 non-null  int64
 23  Retraso en la llegada en minutos      25976 non-null  object
 24  Satisfacción                          25976 non-null  object
dtypes: int64(19), object(6)
memory usage: 5.0+ MB

In [ ]:
# verificar valores con error o valores problemáticos
df['Retraso en la llegada en minutos'] = pd.to_numeric(df['Retraso en la llegada en minutos'], errors='coerce')

In [ ]:
df['Retraso en la llegada en minutos'].isna().sum() # transformamos los valores inválidos

np.int64(83)

In [ ]:
df['Retraso en la llegada en minutos'].fillna(0, inplace=True) #Revisamos si hay NaN

In [ ]:
df['Retraso en la llegada en minutos'] = df['Retraso en la llegada en minutos'].astype('int64') #rellenamos con 0 los NaN

In [ ]:
df.info()      # muestra tipos de datos y valores no nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25976 entries, 0 to 25975
Data columns (total 25 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   id_Encuesta                           25976 non-null  int64
 1   Identificación                        25976 non-null  int64
 2   Género                                25976 non-null  object
 3   Tipo de Cliente                       25976 non-null  object
 4   Edad                                  25976 non-null  int64
 5   Tipo de Viaje                         25976 non-null  object
 6   Clase                                 25976 non-null  object
 7   Distancia de Vuelo                    25976 non-null  int64
 8   Servicio de wifi a bordo              25976 non-null  int64
 9   Hora de salida/llegada conveniente    25976 non-null  int64
 10  Facilidad de reserva en línea         25976 non-null  int64
 11  Ubicación de la puerta                25976 non-null  int64
 12  Comida y bebida                       25976 non-null  int64
 13  Embarque en línea                     25976 non-null  int64
 14  Comodidad del asiento                 25976 non-null  int64
 15  Entretenimiento a bordo               25976 non-null  int64
 16  Servicio a bordo                      25976 non-null  int64
 17  Servicio de espacio para las piernas  25976 non-null  int64
 18  Manejo de equipaje                    25976 non-null  int64
 19  Servicio de facturación               25976 non-null  int64
 20  Servicio a bordo.1                    25976 non-null  int64
 21  Limpieza                              25976 non-null  int64
 22  Retraso en la salida en minutos       25976 non-null  int64
 23  Retraso en la llegada en minutos      25976 non-null  int64
 24  Satisfacción                          25976 non-null  object
dtypes: int64(20), object(5)
memory usage: 5.0+ MB

In [1]:
# Gráfico de barras sobre Satisfacción de Clientes en Aereolíneas según género
sns.set_style("white")
plt.figure(figsize=(10, 5))
plt.title('Satisfacción del Cliente según género')
sns.countplot(data=df, x='Género', hue='Satisfacción', palette='Set2')
# Agregar etiquetas de datos
ax = sns.countplot(data=df, x='Género', hue='Satisfacción', palette='Set2')
# Agregar etiquetas en cada barra
for p in ax.patches:
    altura = p.get_height()
    ax.annotate(f'{int(altura)}',  # convierte a entero
                (p.get_x() + p.get_width() / 2., altura),  # posición
                ha='center', va='bottom', fontsize=8, color='grey', xytext=(0, 5), textcoords='offset points')

NameError: name 'sns' is not defined